# Generated by Django 4.2.7 on 2024-01-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="images",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ImageField(upload_to="images/create/"),
        ),
        migrations.AlterField(
            model_name="post_list",
            name="hashtags",
            field=models.ManyToManyField(related_name="Hashtag", to="app_blog.hashtag"),
        ),
        migrations.AlterField(
            model_name="post_list",
            name="picter",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
