# Generated by Django 4.2.7 on 2024-01-05 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_resourse_center", "0002_rename_post_document_document"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="Document",
            new_name="post",
        ),
    ]
