# Generated by Django 4.2.7 on 2024-01-02 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_trader_academy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="strategylesson",
            name="lesson",
        ),
    ]
